services:
  mysql-master:
    build:
      context: ./master-config
      dockerfile: Dockerfile
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}   
    volumes:
      - ./master-config/data:/var/lib/mysql
      - ./master-config/conf/master.cnf:/etc/mysql/conf.d/master.cnf
    ports:
      - "3306:3306"

  mysql-slave1:
    build:
      context: ./slave1-config
      dockerfile: Dockerfile
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}
    volumes:
      - ./slave1-config/data:/var/lib/mysql
      - ./slave1-config/conf/slave.cnf:/etc/mysql/conf.d/slave.cnf
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master

  mysql-slave2:
    build:
      context: ./slave2-config
      dockerfile: Dockerfile
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}
    volumes:
      - ./slave2-config/data:/var/lib/mysql
      - ./slave2-config/conf/slave.cnf:/etc/mysql/conf.d/slave.cnf
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PROXY_MONITOR_PASSWORD: ${MYSQL_MONITOR_PASSWORD}
    ports:
      - "6033:6033"
      - "6032:6032"
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf

volumes:
  mysql-master-data:
  mysql-slave1-data:
  mysql-slave2-data:
